name: useful_hook
description: "A useful hook for flutter."
version: 0.0.3

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  meta: ^1.10.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.8

  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
